new Vue({
    el:'#vue-app',
    data:{
        newData:{
            empName:'',
            salary:0
        },
        empGroup:[
        {
            empName:"สมพร",
            salary:5000
        },
        {
            empName:"สมศรี",
            salary:4000
        },
        ]
    }
})